version: '2'
services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=somegloriouspassword
      - MYSQL_DATABASE=craft_cms
